In [23]:
import torch
import torch.nn as nn
import torch.optim as optim
import pandas as pd
import numpy as np


data = pd.read_csv("../data/regression/square-simple-test.csv")
X = data['x'].values
Y = data['y'].values
x_scaling_factor = max(X)-min(X)
y_scaling_factor = max(Y)-min(Y)
X_scaled = X/x_scaling_factor
Y_scaled = Y/y_scaling_factor




model = nn.Sequential(
    nn.Linear(1, 5),
    nn.Sigmoid(),
    nn.Linear(5, 5),
    nn.Sigmoid(),
    nn.Linear(5, 1),
)





x_tensor = torch.tensor(X_scaled, dtype=torch.float32).view(-1, 1) 
target = torch.tensor(Y_scaled, dtype=torch.float32).view(-1, 1)  

criterion = nn.MSELoss()
optimizer = optim.Adam(model.parameters(), lr=3e-2)
scheduler = optim.lr_scheduler.StepLR(optimizer, step_size=500, gamma=0.99)

for epoch in range(30000):
    optimizer.zero_grad()
    output = model(x_tensor)
    loss = criterion(output, target)
    loss.backward()
    optimizer.step()
    scheduler.step()

    if epoch % 1000 == 0:
        print(f"Epoch {epoch}, Loss: {loss.item():.4f}")

for name, param in model.named_parameters():
    print(f"{name}: {param.data}")




Epoch 0, Loss: 0.3815
Epoch 1000, Loss: 0.0000
Epoch 2000, Loss: 0.0000
Epoch 3000, Loss: 0.0000
Epoch 4000, Loss: 0.0000
Epoch 5000, Loss: 0.0000
Epoch 6000, Loss: 0.0000
Epoch 7000, Loss: 0.0000
Epoch 8000, Loss: 0.0003
Epoch 9000, Loss: 0.0000
Epoch 10000, Loss: 0.0000
Epoch 11000, Loss: 0.0000
Epoch 12000, Loss: 0.0000
Epoch 13000, Loss: 0.0001
Epoch 14000, Loss: 0.0000
Epoch 15000, Loss: 0.0000
Epoch 16000, Loss: 0.0000
Epoch 17000, Loss: 0.0000
Epoch 18000, Loss: 0.0000
Epoch 19000, Loss: 0.0000
Epoch 20000, Loss: 0.0000
Epoch 21000, Loss: 0.0000
Epoch 22000, Loss: 0.0000
Epoch 23000, Loss: 0.0000
Epoch 24000, Loss: 0.0000
Epoch 25000, Loss: 0.0000
Epoch 26000, Loss: 0.0000
Epoch 27000, Loss: 0.0000
Epoch 28000, Loss: 0.0000
Epoch 29000, Loss: 0.0000
0.weight: tensor([[-6.2809],
        [ 0.1259],
        [ 7.7633],
        [-8.5528],
        [-7.8649]])
0.bias: tensor([-2.5135, -3.7897, -3.9574,  5.3898,  1.5087])
2.weight: tensor([[ 4.4524, -0.3013,  0.9354, -2.0774, -1.8017],


In [31]:
pred_scaled = np.squeeze(model(x_tensor).detach().numpy())
pred_descaled = pred_scaled*y_scaling_factor

In [32]:
pred_descaled

array([ -43.48402736,    3.96473673, -128.54936545,    5.67173979,
        -27.28418227,   36.37571563,  -56.46690486,  164.00017971,
       -109.97554996,  -43.87265617,  -36.55187268, -117.89870597,
          5.24271538, -128.49594277,  -60.9052061 ,    2.96225587,
        -66.2687797 ,   45.75780903,  -35.3845765 ,  -60.03212685,
        152.81125492, -113.81053529,  -97.05217938,  -71.04317744,
       -117.63735882,  -61.75496592, -129.29393347, -116.25093424,
        -22.26591635,  -65.32256226,  -29.81323743, -129.48447436,
       -129.56242484, -127.05215241, -129.8191505 ,  -35.88879545,
         42.80013224, -100.5959263 ,   17.47337185,   -2.155266  ,
        134.30220383,   77.53865469, -116.23202431,  -98.55681224,
        -21.34918738,  -17.81413224,  134.13667832,   16.50794769,
        -33.82837592, -108.21126591,  -69.84818414,    9.34073322,
        -30.88550696,  -31.0298542 ,   10.17861073,   25.51891244,
       -118.40929536,  -19.57222604,  -20.71400866,  -28.76119

In [34]:
sum((Y-pred_descaled)**2)

np.float64(2.596632287882184)

In [35]:
print(model.named_parameters)

<bound method Module.named_parameters of Sequential(
  (0): Linear(in_features=1, out_features=5, bias=True)
  (1): Sigmoid()
  (2): Linear(in_features=5, out_features=5, bias=True)
  (3): Sigmoid()
  (4): Linear(in_features=5, out_features=1, bias=True)
)>


In [37]:
for name, param in model.named_parameters():
    print(f"{param.data}")

tensor([[-6.2809],
        [ 0.1259],
        [ 7.7633],
        [-8.5528],
        [-7.8649]])
tensor([-2.5135, -3.7897, -3.9574,  5.3898,  1.5087])
tensor([[ 4.4524, -0.3013,  0.9354, -2.0774, -1.8017],
        [ 3.2192, -1.4413,  0.0539, -1.5115, -1.4595],
        [-3.8797, -0.3979, -1.6702,  0.4372,  0.4961],
        [ 3.1689, -0.4960,  0.5100, -1.6897, -1.8446],
        [-1.9521, -0.1455, -1.9039,  0.5249,  1.3781]])
tensor([-0.1595, -1.4147, -0.8072,  0.1027, -0.2372])
tensor([[ 1.0611,  0.2838, -0.7706,  0.7969, -0.5539]])
tensor([0.3074])
